import os
import pandas as pd
import google.generativeai as genai
from flask import Flask, request, jsonify, render_template
from werkzeug.utils import secure_filename
from dotenv import load_dotenv

# Load environment variables from a .env file
load_dotenv()

# --- Flask App Initialization ---
app = Flask(__name__, template_folder='templates', static_folder='static')
app.config['UPLOAD_FOLDER'] = 'uploads'
os.makedirs(app.config['UPLOAD_FOLDER'], exist_ok=True)

# --- Gemini API Configuration ---
try:
    gemini_api_key = os.getenv("GEMINI_API_KEY")
    if not gemini_api_key:
        raise ValueError("GEMINI_API_KEY not found in environment variables.")
    genai.configure(api_key=gemini_api_key)
    model = genai.GenerativeModel('gemini-1.5-flash')
except Exception as e:
    print(f"Error configuring Gemini API: {e}")
    model = None

# --- Helper Functions ---

def create_data_profile(df):
    """
    Analyzes a pandas DataFrame and creates a text-based profile.
    
    Args:
        df (pd.DataFrame): The input DataFrame.

    Returns:
        str: A string containing the data profile.
    """
    profile = f"Columns: {', '.join(df.columns.tolist())}\n\n"
    profile += f"Number of rows: {len(df)}\n\n"
    profile += "Data Summary:\n"

    for col in df.columns:
        # Check if column is numeric
        if pd.api.types.is_numeric_dtype(df[col]):
            desc = df[col].describe()
            profile += f"- {col} (Numeric): Avg={desc.get('mean', 0):.2f}, Min={desc.get('min', 0)}, Max={desc.get('max', 0)}\n"
        else:
            # Treat as categorical/text
            unique_values = df[col].nunique()
            if unique_values < 20:
                top_examples = df[col].dropna().unique()[:3]
                examples_str = '", "'.join(map(str, top_examples))
                profile += f'- {col} (Categorical): {unique_values} unique values (e.g., "{examples_str}")\n'
            else:
                profile += f"- {col} (Text/ID): {unique_values} unique values\n"
    return profile

def generate_analysis_prompt(profile):
    """
    Creates a dynamic prompt for the Gemini API based on the data profile.

    Args:
        profile (str): The data profile generated by create_data_profile.

    Returns:
        str: The complete prompt for the LLM.
    """
    return f"""
        You are an expert data analyst. A user has uploaded a CSV file. Your task is to act as a helpful assistant and suggest 3-5 potential types of insightful data analysis that could be performed on this dataset.

        For each suggestion, provide a clear title, briefly explain what business question it would answer, and mention which columns would be used. The tone should be professional, encouraging, and easy to understand for a business user.

        Do not perform the analysis yourself. Only suggest what is possible. Format your response in Markdown.

        ### Data Profile ###
        {profile}
        ### End of Data Profile ###

        Your suggestions for analysis:
    """

# --- Flask Routes ---

@app.route('/')
def index():
    """Renders the main HTML page."""
    return render_template('index.html')

@app.route('/analyze', methods=['POST'])
def analyze_csv():
    """
    Handles the CSV file upload, analysis, and returns suggestions.
    """
    if not model:
        return jsonify({"error": "AI model is not configured. Please check your GEMINI_API_KEY."}), 500

    if 'file' not in request.files:
        return jsonify({"error": "No file part in the request"}), 400
    
    file = request.files['file']

    if file.filename == '':
        return jsonify({"error": "No file selected"}), 400

    if file and file.filename.endswith('.csv'):
        try:
            filename = secure_filename(file.filename)
            filepath = os.path.join(app.config['UPLOAD_FOLDER'], filename)
            file.save(filepath)

            # Read CSV into a pandas DataFrame
            df = pd.read_csv(filepath)
            
            # Clean up the uploaded file
            os.remove(filepath)

            if df.empty:
                return jsonify({"error": "CSV file is empty."}), 400

            # Generate the data profile and prompt
            profile = create_data_profile(df)
            prompt = generate_analysis_prompt(profile)

            # Call the Gemini API
            response = model.generate_content(prompt)
            
            # Return the generated content
            return jsonify({"analysis": response.text})

        except Exception as e:
            return jsonify({"error": f"An error occurred: {str(e)}"}), 500
    else:
        return jsonify({"error": "Invalid file type. Please upload a CSV file."}), 400

# --- Main Execution ---
if __name__ == '__main__':
    # It's recommended to use a production-ready server like Gunicorn or Waitress
    # For development, the Flask server is sufficient.
    app.run(debug=True, port=5001)
